### PR TITLE
Trading Module

### PR DESCRIPTION
**Pull request by aminroosta**
@arnab I was trying to implement a beta version, and now i think i have delivered.
I have a checklist on the *implement trading module* task that needs to be done before considering this DONE.
Please review this PR, i need your code review feedback. 

deployed to aminroosta.ir/webtrader/amintrading

### CODE REVIEW

**Comment by arnabk** [comment]
@aminroosta Code review comments

* shine - why this class no namespace? Meant for all to use? If yes, then put it in main.css

* Please do not use following code -
setTimeout(function(){
       cb(data);		      
},0);
Use $(document).oneTime(…);

* Same with setInterval(refresh_active_symbols, 60*1000);
Use $(document).everyTime()

* Please review css classes in tradeDialog.css file. Make sure that namespace is properly used. We might have to work on changing UI in future and I want to make sure that we do the UI look and feel switch smoothly.

**Comment by ashkanx** [comment]
is  text-shadow part of mockup?

**Comment by ashkanx** [comment]
Tick didn't work when trying to make the second purchase
image
this is console:
image

**Comment by ashkanx** [comment]
image
alignment issue

**Comment by ashkanx** [comment]
image
I can’t key in a value manually.

**Comment by ashkanx** [comment]
image
what does this do?

**Comment by ashkanx** [comment]
image
error when trying to get  Gold/USD

**Comment by ashkanx** [comment]
image
after few time changing Duration/End Time, this happened
error in console: Uncaught TypeError: Cannot read property 'contract_type' of undefined

**Comment by aminroosta** [comment]
@ashkanx  i fixed the design problems today, 
i was unable to reproduce scripts errors though.

@arnabk i have refactored most of tradeDialog.css for design problems ashkan mentioned.
about using *oneTime* and *everyTime*, i this we should remove that library from the project.

**Pull request merged**
