### PR TITLE
Fix for broken IE flexbox implemenation + Chane the website title.

### PR DESCRIPTION
**Pull request by aminroosta**

### CODE REVIEW

**Comment by aminroosta** [comment]
deployed to aminroosta.ir/webtrader/amintrading

**Comment by ashkanx** [comment]
@arnabk We need to modify the report in GA accordingly. The report filters the data using website title.

**Comment by aminroosta** [comment]
Add fix for rivetjs selectmenu binding

**Comment by arnabk** [comment]
@ashkanx What changes do you want?

**Pull request merged**
