### PR TITLE
disable reset options

### PR DESCRIPTION
**Pull request by 4p00rv**

### CODE REVIEW

**Comment by arnabk** [comment]
@4p00rv I recommend submitting this to master because its better to keep this open in beta for testing later when backend is ready for it. No client uses beta, so we are safe.

@ashkanx any comments?

**Comment by 4p00rv** [comment]
@arnabk I agree. But let us wait for Ashkan's comment.

**Comment by ashkanx** [comment]
Agree

**Comment by arnabk** [comment]
@4p00rv Closing. Please send a new PR for master

**Pull request closed without merging**
